stages:
  - pages

pages:
  stage: pages
  image: ghcr.io/quarto-dev/quarto-full:latest
  # Functions that should be executed before the build script is run
  before_script:
    - tlmgr option repository http://mirror.ctan.org/systems/texlive/tlnet
    - tlmgr update --self --verify-repo=none
    - tlmgr install beamer caption soul koma-script --verify-repo=none
  script:
    - quarto render . --output-dir public
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - public

