stages:
  - deploy

pages:
  stage: deploy
  image: ghcr.io/quarto-dev/quarto-full:latest
  script:
    - quarto render . --output-dir public
  artifacts:
    paths:
      - public
  only:
    - main  # Change to your default branch if it's not "main"
