stages:
  - lint
  - test
  - build
  - deploy
  - pages

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: tcp://docker:2375
  IMAGE_NAME: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}
  PYTHON_VERSION: "3.9"
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.pip-cache"



# Build Docker image
build:
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: ""
    IMAGE_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker-compose -f docker-compose.build.yml up
    # No need for docker tag command since we're using the correct image name in docker-compose.build.yml
  after_script:
    - docker logout $CI_REGISTRY


# Generate and publish project documentation
pages:
  stage: pages
  image: ghcr.io/quarto-dev/quarto-full:latest
  before_script:
    - tlmgr option repository https://mirror.ctan.org/systems/texlive/tlnet
    - tlmgr update --self --verify-repo=none
    - tlmgr install beamer caption soul koma-script --verify-repo=none
    - apt-get update && apt-get install -y librsvg2-bin
  script:
    - echo "Rendering Quarto documentation..."
    - quarto render . --output-dir public
  artifacts:
    paths:
      - public
  only:
    - main

deploy_to_ec2:
  stage: deploy
  script:
    - echo "Deploying to EC2..."
    - chmod 600 $EC2_DEPLOY_KEY
    - ssh -i $EC2_DEPLOY_KEY -o StrictHostKeyChecking=no ubuntu@54.227.121.145 "
      cd /home/ubuntu/02 &&
      git fetch origin &&
      git checkout Navid/Cleaning-up-for-aws &&
      git reset --hard origin/Navid/Cleaning-up-for-aws &&
      sudo docker-compose down &&
      sudo docker-compose up -d --build "