version: '3'

services:
  test:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - pip-cache:/root/.cache/pip
    working_dir: /app
    command: >
      bash -c "
        pip install pytest pytest-xdist pytest-cov flake8 &&
        echo 'Running pytest with parallel execution...' &&
        python -m pytest src/ -v --numprocesses auto --cov=src --cov-report=xml"
    environment:
      - PYTHONPATH=/app
      - PYTEST_ADDOPTS=--numprocesses auto

volumes:
  pip-cache: 