C4Dynamic
title Dynamic Diagram for Inference Pipeline

%% Participants


System_Boundary(s, "Solarpanel Detection System"){
    ContainerDb(minio, "MinIO", "Object Store (S3-compatible)", "Holds inference images and possibly model artifacts")
    Container_Boundary(airflow, "Airflow") {
        Component(inferenceDag, "Inference DAG", "Python/Airflow DAG", "Schedules and orchestrates the inference tasks daily")
    }
    Container_Boundary(pipeline, "Solardetection Service"){
        Component(inference, "Inference Pipeline", "Python", "Executes solar panel detection (YOLO model)")
        Component(training, "Training Pipeline", "Python", "Trains/updates the detection model using collected images.")
        Component(webscraping, "Webscraping Process", "Python", "Part of the Solardetection Service container.")

    }

}


%% Relationships (steps in the process)
Rel(inferenceDag, minio, "Checks periodically for new inference data", "S3/HTTP")
Rel(inferenceDag, inference , "Triggers solar panel detection task if new data", "Internal call")
Rel(inference , minio, "", "S3/HTTP")
Rel(inference,      minio, "Loads YOLO model / images + Writes detection results in  a CSV File", "S3 / HTTP")  


UpdateRelStyle(user, minio, $textColor="#ef4444", $lineColor="#ef4444", $offsetX="0", $offsetY="-40")
UpdateRelStyle(inferenceDag, minio, $textColor="#3b82f6", $lineColor="#3b82f6", $offsetX="-190", $offsetY="-50")
UpdateRelStyle(inferenceDag, inference , $textColor="#3b82f6", $lineColor="#3b82f6", $offsetX="-100", $offsetY="50")
UpdateRelStyle(inference , minio, $textColor="#a855f7", $lineColor="#a855f7", $offsetX="-100", $offsetY="-40")
UpdateRelStyle(inference , postgres, $textColor="#a855f7", $lineColor="#a855f7", $offsetX="-40", $offsetY="-60")
