C4Deployment
title Deployment Diagram for Solar Panel Detection System (AWS)

%% The top-level node represents our aws environment
Deployment_Node(aws, "Amazon Web Services (AWS)", "Cloud Environment") {
   
        Container(airflow, "Airflow", "Docker Container", "")
        Container(pipeline, "Solardetection Service", "Docker Container ", "")
        Container(fastapi, "FastAPI Gateway", "Docker Container ", "")
        Container(mlflow, "MLflow", "Docker Container ", "")
        ContainerDb(postgres, "PostgreSQL", "Docker Container", "")
        ContainerDb(minio, "MinIO", "Docker Container", "")
    }

Rel(airflow, pipeline, "")
Rel(pipeline, minio, "", "")
Rel(pipeline, mlflow, "", "")
Rel(pipeline, postgres, "", "")
Rel(fastapi, pipeline, "", "")
Rel(mlflow, minio, "", "")
Rel(mlflow, postgres, "", "")

%% Example styling offsets with colors
%% "The arrows from the same container to another should have the same color."

%% Airflow -> Pipeline
UpdateRelStyle(airflow, pipeline, $lineColor="#3b82f6", $textColor="#3b82f6", $offsetX="-110", $offsetY="-110")

%% Pipeline -> MinIO, MLflow, PostgreSQL all share the same style
UpdateRelStyle(pipeline, minio, $lineColor="#a855f7", $textColor="#a855f7", $offsetX="0", $offsetY="-20")
UpdateRelStyle(pipeline, mlflow, $lineColor="#a855f7", $textColor="#a855f7", $offsetX="-140", $offsetY="0")
UpdateRelStyle(pipeline, postgres, $lineColor="#a855f7", $textColor="#a855f7", $offsetX="-50", $offsetY="0")

%% FastAPI -> Pipeline
UpdateRelStyle(fastapi, pipeline, $lineColor="#15803d", $textColor="#15803d", $offsetX="-100", $offsetY="-110")

%% MLflow -> MinIO, PostgreSQL both share the same style
UpdateRelStyle(mlflow, minio, $lineColor="#f97316", $textColor="#f97316", $offsetX="110", $offsetY="60")
UpdateRelStyle(mlflow, postgres, $lineColor="#f97316", $textColor="#f97316", $offsetX="-80", $offsetY="50")
UpdateLayoutConfig($c4ShapeInRow="3", $c4BoundaryInRow="1")

